### ISSUE TITLE
Explanation for scaling, units, z-scores

### ISSUE THREAD

**Issue by giacomobg** [ONSvisual/subnational-indicators#10]
The way the unit is included with the name of the measure, it gives the impression that's what's shown on the jitter plot. For example, Smokers (%) gives the impression that the jitter plot shows % which would naturally go small to big.

It should be clear that the plot does not show % smokers going small to big but instead shows where smoking is more of a problem to smoking is less of a problem than average.

Possible solutions
- redesign the placement and style of the unit, or combine with #8 and move unit to table
- add line of explanation of z-score scaling at top
- redesign emphasis or styling of positive and negative axis labels at top of jitter

**Comment by henryjameslau** [comment]
This is for the subnational team to do so will close it
