### ISSUE TITLE
To fix

### ISSUE THREAD

**Issue by henryjameslau** [ONSvisual/subnational-indicators#32]
- reorder colours so light blue isn't second
- arrows on positive and negative are different sizes 
- check tooltips are in the right place when the page is embedded

**Comment by henryjameslau** [comment]
Remove the expandy twisty detail for select areas to compare

**Comment by henryjameslau** [comment]
Fixed by https://github.com/ONSvisual/subnational-indicators/commit/ab2ef0a4a38af94ee0de9dd364a62e8d4f638b2a, https://github.com/ONSvisual/subnational-indicators/commit/0f986e5c0c937359d5d0fb6b47fad9de1041d618 and https://github.com/ONSvisual/subnational-indicators/commit/febc6a5833777438e75ddd21c803101e67822209

**Comment by henryjameslau** [comment]
Embeds aren't the right width though and the top table is reappended on page resizing so not quite all fixed

**Comment by rcatlord** [comment]
Could the final colour be #F66068 rather than #27A0CC on febc6a5833777438e75ddd21c803101e67822209? We'd then have different colours for each selection. If not colourblind friendly then feel free to ignore.
