### ISSUE TITLE
Add colour gradient to the dots

### ISSUE THREAD

**Issue by henryjameslau** [ONSvisual/subnational-indicators#6]
Add some good/bad colours to the dots so they are easier to read, perhaps shades of colours for each SD away from the mean.

**Comment by rcatlord** [comment]
I tried this with my final [prototype](https://observablehq.com/d/1234207fb77c2bab). PHE use a similar *categorical* colour scheme with their [spine charts](https://fingertips.phe.org.uk/documents/PHDS%20Guidance%20-%20Spine%20Charts.pdf).       
![prototype](https://user-images.githubusercontent.com/12719575/136782494-6f897734-88a9-4ea2-b037-75988b1c2293.png)

**Comment by fryford** [comment]
Think this works well when you only have one area selected. Not sure how it would work when you've got more than one?

**Comment by rcatlord** [comment]
The position rather than the colour of the dots indicates whether they are ‘negative’, ‘neutral’ or ‘positive’.
